gui:
  theme:
    activeBorderColor:
      - "#80a0ff"
      - bold

    inactiveBorderColor:
      - "#5a5a5a"

    selectedLineBgColor:
      - "#2a2a2a"

    cherryPickedCommitBgColor:
      - "#3a3a00"

    cherryPickedCommitFgColor:
      - "#ffaf00"

    unstagedChangesColor:
      - "#ff5454"

    defaultFgColor:
      - "#c6c6c6"

    searchingActiveBorderColor:
      - "#80a0ff"
      - bold

  nerdFontsVersion: "3"

git:
  overrideGpg: true
